fix: directory copy
hashicorp/packer-plugin-lxc pull request #39
Opened 2022-06-30 16:24 UTC by devashish-patel

- The upload directory function currently adds `/.` at the end of the `source` path, which changes the behavior of the `cp`. 
- The change in this PR relies on the user input if the source ends with `/.` we only copy the content of the directory otherwise the while source directory to the destination.

Resolves #31

2022-06-30 16:24 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/packer-plugin-lxc?pullRequest=39)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/packer-plugin-lxc?pullRequest=39)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/packer-plugin-lxc?pullRequest=39).</sub>

2022-07-01 08:51 UTC, sylviamoss approved these changes
Nice catch!

2022-07-06 12:08 UTC, nywilken requested changes
This changes the documented behavior for the file provisioner when running on lxc. With this change source directories with the trailing slash copies the parent source directory along with its contents. But it should only copy the contents.

2022-07-06 12:08 UTC, nywilken commented on builder/lxc/communicator.go
> +	cpCmd, err := c.CmdWrapper(fmt.Sprintf("cp -R %s %s", src, dest))
According to the docs if the source path contains a trailing slash on the contents of the directory will get uploaded on to the container. Requiring the user to include a trailing slash-dot `/.` changes the expected behavior. 

Suggested change
```go
// Source directories with a trailing slash should only copy the contents of the directory
if strings.HasSuffix(src, "/") {
  src = fmt.Sprintf("%s/.",src)
}
cpCmd, err := c.CmdWrapper(fmt.Sprintf("cp -R %s %s", src, dest))
```

2022-07-06 15:38 UTC, nywilken approved these changes
Nicely done. The changes look good.

2022-07-06 15:38 UTC, merged